[versions]
gmp = '1.8.15'
annotations = '26.0.2'
jupiter = '5.12.1'

[plugins]
gmp = { id = 'org.javamodularity.moduleplugin', version.ref = 'gmp' }

[libraries]
annotations = { module = 'org.jetbrains:annotations', version.ref = 'annotations' }
jupiter = { module = 'org.junit.jupiter:junit-jupiter', version.ref = 'jupiter' }
jupiterRuntime = { module = 'org.junit.platform:junit-platform-launcher' }
