name: 'Deploy'

on:
  create:
    branches:
      - 'master'

jobs:
  deploy:
    if: startsWith(github.repository, 'noeppi-noeppi/') && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: 'Setup Java'
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 'Build ModuleBootstrap'
        run: |
          ./gradlew \
          -Pversion=${{ github.ref_name }} \
          -PtuxtownUsername=${{ secrets.PUBLISH_USER }} \
          -PtuxtownPassword=${{ secrets.PUBLISH_PASSWORD }} \
          build publish
